apiVersion: v1
kind: Pod
metadata:
  name: vanity
spec:
  containers:
  - name: vanity
    image: wh3rd/vanity
    ports:
    - containerPort: 8080
      hostPort: 80
    - containerPort: 8443
      hostPort: 443
